name: lexicography
version: 0.1.0.0
github: "satosystems/c-language-divination"
license: BSD3
author: "Satoshi Ogata"
maintainer: "satosystems@gmail.com"
copyright: "(c) 2023 Satoshi Ogata"

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/satosystems/c-language-divination/haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - directory
  - html-conduit
  - http-conduit
  - string-conversions
  - text
  - xml-conduit

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  lexicography:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lexicography
